/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BEU.Curso;
import BEU.Estudiante;
import BLL.GestionCurso;
import BLL.GestionEstudiante;
import BLL.GestionMatricula;
import Lucas.Util;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author labctr
 */
public class frmRegistromatricula extends javax.swing.JInternalFrame {
    
    private final String titulo = "Registro de Matricula";
    //Servicio //Bussiness logic layer 
    private GestionCurso cursosBLL=new GestionCurso();
    private List<Curso> cursos;
     private GestionEstudiante estudianteBLL=new GestionEstudiante();
       private List<Estudiante> estudiantes;
       private GestionMatricula matriculaBLL =new GestionMatricula();
    
       private boolean Validar(){
           Curso cr =(Curso) this.cbmcurso.getSelectedItem();
           if(cr.getTitulo().equals("-Seleccione-")){
               vtnPrincipal.verMensaje("Curso no Valido....", titulo, JOptionPane.WARNING_MESSAGE);
               return false;
           }
          Estudiante est =(Estudiante)this.cbmestudiante.getSelectedItem();
           if(est.equals("-Seleccione-")){
               vtnPrincipal.verMensaje("Estudiante no Valido....", titulo, JOptionPane.WARNING_MESSAGE);
               return false;
           }
           return true;
       }
       private void  CrearMatricula() throws IOException{
          
          Curso cr =(Curso) this.cbmcurso.getSelectedItem();
          Estudiante est =(Estudiante)this.cbmestudiante.getSelectedItem();
          this.matriculaBLL.crear();
          this.matriculaBLL.configurar(cr, est);
          this.matriculaBLL.archivar();
    
          
       }
    
    private void LeerCursos(){
         try{
             Curso ficticio = new Curso("-Seleccione-",0.0f,"");
             ficticio.setTitulo("-Seleccione-");
             this.cbmcurso.addItem(ficticio);
           cursos=cursosBLL.getCursos();
          // for(Curso c :cursos){
            //   this.cbmcurso.addItem(c);
           //}
           //EXPRESION LAMBDA
           cursos.forEach((c)->{
               this.cbmcurso.addItem(c);
           });
       }catch(Exception e){
           Util.print("ERROR:"+ e.toString());
           vtnPrincipal.verMensaje("Error al leer los cusos" ,titulo, JOptionPane.ERROR_MESSAGE);
           
       }
        
    }
      
      private void LeerEstudiantes(){
         try{
              Estudiante ficticio = new Estudiante();
              ficticio.setNombre("-Seleccione-");
              ficticio.setApellido("");
              this.cbmestudiante.addItem(ficticio);
           estudiantes=estudianteBLL.LeerEstudiantes();
          // for(Curso c :cursos){
            //   this.cbmcurso.addItem(c);
           //}
           //EXPRESION LAMBDA
           estudiantes.forEach((est)->{
               this.cbmestudiante.addItem(est);
           });
       }catch(Exception e){
           Util.print("ERROR:"+ e.toString());
           vtnPrincipal.verMensaje("Error al leer los cusos" ,titulo, JOptionPane.ERROR_MESSAGE);
           
       }
        
    }
  
    public frmRegistromatricula() {
        initComponents();
        LeerCursos();
        LeerEstudiantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblestudiante = new javax.swing.JLabel();
        lblcurso = new javax.swing.JLabel();
        cbmestudiante = new javax.swing.JComboBox<>();
        cbmcurso = new javax.swing.JComboBox<>();
        bntguardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(182, 26, 211));
        setForeground(new java.awt.Color(247, 145, 210));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/registro.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 227, 293));

        jLabel2.setFont(new java.awt.Font("Bitstream Charter", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(235, 25, 191));
        jLabel2.setText("REGISTRO DE MATRICULA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        lblestudiante.setFont(new java.awt.Font("Bitstream Charter", 2, 24)); // NOI18N
        lblestudiante.setText("Estudiante:");
        getContentPane().add(lblestudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        lblcurso.setFont(new java.awt.Font("Bitstream Charter", 2, 24)); // NOI18N
        lblcurso.setText("Curso:");
        getContentPane().add(lblcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        getContentPane().add(cbmestudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 390, -1));

        getContentPane().add(cbmcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 390, -1));

        bntguardar.setFont(new java.awt.Font("Bitstream Charter", 2, 24)); // NOI18N
        bntguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/save.png"))); // NOI18N
        bntguardar.setText("Guardar");
        bntguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntguardarActionPerformed(evt);
            }
        });
        getContentPane().add(bntguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntguardarActionPerformed
       try{
           if(Validar()){
                 CrearMatricula();
            vtnPrincipal.verMensaje("Matricula Creada Correctamente....", titulo, JOptionPane.WARNING_MESSAGE);
           }
           
       }catch(Exception e){
           Util.print("ERROR:"+ e.toString());
           vtnPrincipal.verMensaje("Error al crear  la matricula" ,titulo, JOptionPane.ERROR_MESSAGE);
           
       }
    }//GEN-LAST:event_bntguardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntguardar;
    private javax.swing.JComboBox<Curso> cbmcurso;
    private javax.swing.JComboBox<Estudiante> cbmestudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblcurso;
    private javax.swing.JLabel lblestudiante;
    // End of variables declaration//GEN-END:variables
}
